src/lib.rs
tests/openssl.rs

Hey, would you be interested in merging something like this? Seems like a feature that mostly fits, at least, although it maybe widens the scope a bit.
On the other hand, I'm not sure how best to test this for now (although I suppose the openssl library exposes API to actually handle CSRs). So far this is based on just comparing openssl-generated CSRs with the JS ASN.1 thingy you point to in your README.

Add support for writing certificate signing requests

---

src/lib.rs

Distinguished names were serialized "the wrong way around". See https://tech.labs.oliverwyman.com/blog/2007/10/30/whats-in-a-distinguished-name/.

Fixing serialization of distinguished names

---

src/lib.rs
tests/generic.rs

Offering an interface to obtain a `KeyPair`'s public key in DER and PEM and access `is_compatible()`
Avoiding code duplication by moving public key serialization into `KeyPair`.
Addresses https://github.com/est31/rcgen/issues/15 and https://github.com/est31/rcgen/issues/18

Expose KeyPair interface

---

src/lib.rs

Makes public key easily accessible.
This way the user does not need to serialize to der, then deserialize to get the raw pk.

make KeyPair::public_key public

---

src/lib.rs

I didn't try to understand what the leap second code is doing, but there are 1e9 nanoseconds per second, and changing this removed the millisecond added to my cert.

Correct number of nanoseconds per second

---

Cargo.lock
Cargo.toml

When a similar [yasna pull request][1] is merged, this will save
a dependency on time 0.1; multiple incompatible versions of time
exist (0.1, 0.2, 0.3 soon) and tend to cause duplicate dependencies.
[1]: https://github.com/qnighy/yasna.rs/pull/49

Don't enable chrono default features

---

src/lib.rs

When comparing a CSR generated with the same parameters using openssl,
I noticed that the CSR generated by rcgen was missing attributes data.
OpenSSL:
```
Certificate Request:
Data:
Version: 0 (0x0)
Subject: C=US, ST=., L=., O=., OU=., CN=krustlet
Subject Public Key Info:
Public Key Algorithm: id-ecPublicKey
Public-Key: (256 bit)
pub:
04:3c:2b:64:c2:0e:8f:fa:86:b2:5c:f1:66:82:a7:
73:48:37:3b:d7:f0:12:25:0e:29:c2:65:20:1f:a5:
60:36:52:70:ba:60:7e:00:e0:92:74:fe:dd:0f:8a:
28:0a:6e:1b:41:46:10:96:72:54:5f:3c:d1:e5:86:
59:9b:61:a1:e3
ASN1 OID: prime256v1
NIST CURVE: P-256
Attributes:
a0:00
Signature Algorithm: ecdsa-with-SHA256
30:45:02:20:50:a9:e6:11:9c:46:4b:c2:85:74:f9:58:30:26:
4f:9c:d2:18:5f:33:fb:b6:74:44:3b:47:b1:2c:e8:cc:14:ac:
02:21:00:eb:92:eb:b8:98:89:2e:d2:0e:fe:9c:af:c7:fe:60: …
```

fix(lib): Adds missing context block to CSR

---

Cargo.toml
tests/botan.rs

Building Botan on macOS apparently is not supported upstream:
"Currently, systems other than Windows and POSIX (such as VMS,
MacOS 9, OS/390, OS/400, …) are not supported by the build system,
primarily due to lack of access."
https://botan.randombit.net/handbook/building.html

Disable botan dependency and tests on macOS

---

Cargo.toml
src/lib.rs
tests/openssl.rs
tests/webpki.rs

This PR fixes two bugs:
* Certificates which were signed by a CA using a different signing algorithm than the certificate itself were not usable, because the wrong signing algorithm identifier was serialized for the issuer's signature and in the tbsCertificate. This has been fixed, and tests added.
* Botan was always pulled in as a dependency. It is now only pulled in as a dev-dependency only.

Fix mixed signing algorithms & Botan dependency

---

README.md

Hey :)
I just noticed, that there's an unnecessary `.unwrap()` in the example code of your Readme.
Nothing big.
https://docs.rs/rcgen/0.8.9/rcgen/struct.Certificate.html#method.serialize_private_key_pem
Thanks for providing this library!

Small readme example code fix

---

Cargo.lock
Cargo.toml
src/lib.rs

Here is a proposed implementation for https://github.com/est31/rcgen/issues/47.
This proposition is to have a new optional feature, named `zeroize`. With that option enabled, a dependency to `zeroize` is added and the `Zeroize` trait is implemented for `KeyPair`, and all structures that include such a key pair (`Certificate`, `Certificate`, `CertificateSigningRequest` and `CertificateParams`.

Impl Zeroize for KeyPair and Certificate

---

Cargo.lock
Cargo.toml
tests/botan.rs

PR #42 / ef63ca7235eb64ddc28243ec3b23e5eff0353756 wasn't needed.
The botan author has ensured that their library works on macos just fine.
Closes #52

Re-enable botan test on macos

---

src/lib.rs
src/main.rs
tests/generic.rs

This is another attempt for implementing Hash for `PublicKey`. I analyzed `SignatureAlgorithm::eq` and the solely compared field is `oids_sign_alg`. To my understanding of how collections rely on a `Hash` implementation, hashing any other field in `SignatureAlgorithm` violates this contract: `k1 == k2 -> hash(k1) == hash(k2)`. It looks kinda odd to me. Simple test cases are included, and all are passing.
Besides, `SignAlgo` can implement `Hash` with `std::ptr::hash()`, but this is apparently no longer needed.

Implement Hash for SignatureAlgorithm and PublicKey

---

src/lib.rs

Firefox will complain if the same serial number (defaults to 42) is used with different certificate. This happens if you regenerate the certificate. This patch uses value of the public key (first 8 bytes) as the value for the serial number. This way every certificate will get unique serial number.

Use public key value as a default serial number

---

src/lib.rs

Hello!
I've implemented TryForm<Vec<u8>> trait for KeyPair to be able to call try_from on a Vec<u8>, avoid to create a new Vec<u8> from a slice of u8.
I also refactor the logic the get the kind and algorithm used for the serialized DER for TryForm trait.

Implement TryForm<Vec<u8>> for KeyPair struct

---

src/lib.rs
tests/botan.rs
tests/openssl.rs
tests/webpki.rs

fixes #59
Allows non UTF-8 values to be used for distinguished name entries

feat: support non utf8 strings

---

src/lib.rs

According to [RFC5280](https://datatracker.ietf.org/doc/html/rfc5280#page-38) DNS Name and RFC822 Name are IA5 strings.
```
GeneralName ::= CHOICE {
otherName                       [0]     OtherName,
rfc822Name                      [1]     IA5String,
dNSName                         [2]     IA5String,
x400Address                     [3]     ORAddress,
directoryName                   [4]     Name,
ediPartyName                    [5]     EDIPartyName,
uniformResourceIdentifier       [6]     IA5String,
iPAddress                       [7]     OCTET STRING,
registeredID                    [8]     OBJECT IDENTIFIER }
```
`write_ia5_string` panics if the provided string is not ASCII, perhaps we should add our own `is_ascii` check and return an error instead.

chore: use ia5_string for Rfc822Name and DnsName

---

Cargo.lock
Cargo.toml
src/lib.rs

⚠️ This currently includes `yasna.rs` as a git dependency, because there's no release with https://github.com/qnighy/yasna.rs/pull/61 yet. I wanted to open the PR anyway to indicate the changes, and perhaps motivate a release for `yasna.rs`.
---
Since https://github.com/qnighy/yasna.rs/pull/61 is merged, I wanted to make the corresponding updates here as well, to hopefully resolve #65.
The changes are very mechanically once again, and again the main limitation is that `time` cannot represent leap seconds. This affects some of the logic and removes a test case.
I've checked the output from `main.rs` and the examples with `openssl x509 -in certs/cert.pem -noout -text` and it's as I'd expect. I've also tried it with a library using QUIC w/ self-signed certs and that also works as expected.

Switch from `chrono` to `time`

---

Cargo.lock
Cargo.toml

Despite #66, chrono is still pulled in transitively via x509-parser 0.12. x509-parser 0.13 [switched to time as well](https://github.com/rusticata/x509-parser/blob/master/CHANGELOG.md#0130), so using rcgen with an updated version won't cause `cargo audit` issues.

Update x509-parser to 0.13

---

src/lib.rs

Allows the user to access the DER encoded keypair's bytes without
cloning.
My specific use case is that I'm implementing my own `KeyPair<'_>` type that I use for signing, and without this method I would also need a `OwnedKeyPair` version.

Add KeyPair::serialized_der method

---

Cargo.toml

when time 0.3.0 is used:
```
error[E0277]: the trait bound `time::Month: From<u8>` is not satisfied
--> /Users/anton/.cargo/registry/src/github.com-1ecc6299db9ec823/yasna-0.5.0/src/models/time.rs:97:21
|
97 |         let month = Month::try_from((buf[2] - b'0') * 10 + (buf[3] - b'0')).ok()?;
|                     ^^^^^^^^^^^^^^^ the trait `From<u8>` is not implemented for `time::Month`
|
= note: required because of the requirements on the impl of `Into<time::Month>` for `u8`
= note: required because of the requirements on the impl of `TryFrom<u8>` for `time::Month`
error[E0277]: the trait bound `time::Month: From<u8>` is not satisfied
--> /Users/anton/.cargo/registry/src/github.com-1ecc6299db9ec823/yasna-0.5.0/src/models/time.rs:271:21
|
271 |         let month = Month::try_from((buf[4] - …
```

set min time crate version to 0.3.6

---

.gitignore
examples/rsa-irc.rs
src/lib.rs

Support parsing certificates that have an IP address as a subject alternate name.

Parse an IP address into SanType from a x509 GeneralName.

---

src/lib.rs

supercedes https://github.com/est31/rcgen/pull/113
Guesses what the user meant in some circumstances, email addresses and uri's will still be misunderstood.

CertificateParams::new attempt to parse ip address

---

.github/workflows/ci.yml
Cargo.toml
src/lib.rs
tests/botan.rs

PR in reference to https://github.com/est31/rcgen/issues/115
Adds platform checking to decide what line endings to use when serializing to PEM.
I tried activating Github Actions for Windows to test correctness for that platform too, but unfortunately it seems the dev-dependency `openssl` does not work: https://github.com/frjonsen/rcgen/actions/runs/4655417259/jobs/8238039795

Use line endings appropriate for current platform

---

Cargo.toml

Fixes a regression from d3ab04a84b78bed81c67d21873581302c787fc25 (#118).
See also c8eb1e689dbd1558738090f2a5e3e06117c66d2e (#43).

Turn botan back into a dev-dependency

---

Cargo.lock
Cargo.toml
tests/util.rs
tests/webpki.rs

This is a small follow-up to https://github.com/est31/rcgen/pull/128 now that `rustls/webpki` v0.101.0 has been released. Resolves https://github.com/est31/rcgen/issues/129
The [original webpki](https://github.com/briansmith/webpki) crate is under-maintained, so the [Rustls project](https://github.com/rustls/rustls) has [forked it](https://github.com/rustls/webpki) and invested in maintenance and new features, including [CRL support](https://docs.rs/rustls-webpki/latest/webpki/struct.BorrowedCertRevocationList.html) for client certificate revocation checking.
This commit switches rcgen to use the latest version of the rustls/webpki fork instead of the original upstream webpki project. One small breaking change in the end entity name validation API is fixed in the existing rcgen webpki …

switch to rustls/webpki, add test coverage for CRL parsing.

---

src/lib.rs
tests/botan.rs
tests/generic.rs
tests/openssl.rs
tests/util.rs
tests/webpki.rs

This branch adds support for certificate CRL distribution points extensions, and the corresponding CRL issuing distribution point extension.
Initially I opened this PR with just the former, but the latter is so closely related it felt more appropriate to make one branch with two commits. 
Test coverage is better for the certificate extension compared to the CRL extension, the upstream library support for the latter is quite thin.
I haven't updated the webpki CRL revocation checking tests to demonstrate the new extensions at this time, because it is only available in an alpha release. I can either do this as a follow up once the v/0.102.0 release is cut (likely in O(weeks)) or we could update the dev-dependency to the alpha now and add coverage in this branch. LMK what you would prefer :-) …

lib: add cert and CRL distribution point extension support.

---

tests/util.rs
tests/webpki.rs

Previously the `test_crl` fn generated a certificate revocation list that had a revoked certificate entry with the serial number `0xC0FFEE` - this constant has a binary representation of `110000001111111111101110`, where the MSB is 1. This makes the serial number negative, in contradiction to RFC 5280's requirements for serial numbers.
The Yasna-based encoder that rcgen uses for emitting the serial number accounted for this by prepending 0x00 automatically. This should have resulted in a failure to find the literal serial `0xC0FFEE` in the webpki CRL, except that webpki was incorrectly canonicalizing the serial number for the CRL representation, meaning the `0x00C0FFEE` serial emitted by rcgen was stored as `0xC0FFEE`, matching our lookup and allowing the test to pass.
In Webpki v0.101.2 …

tests: fix webpki CRL test, deprecations.

---

Cargo.lock
Cargo.toml
src/lib.rs

Update to pem >= 3.0.2, which has this PR integrated: https://github.com/jcreekmore/pem-rs/pull/51

Update pem to 3.0.2

---

Cargo.lock
Cargo.toml

Latest version of `time` create has a higher minimum rust version that `rcgen` does.
Limit the version of `time` to the latest version with a minimum rust version compatible with `rcgen`.

Hold back version of time crate to 0.3.23 to support Rust 1.66

---

.github/dependabot.yml

This will let Dependabot keep the CI GitHub action versions up to date.
For the time being we choose not to configure Dependabot for the cargo ecosystem since its generally more noise/work to keep up with.

ci: add dependabot config for GitHub actions.

---

.github/workflows/ci.yml
Cargo.toml

As suggested by @rukai in #144, I agree that libraries should almost never use precise dependency requirements. Given that we have a `Cargo.lock` file, we can use it to stick to the older time release to ensure we can work on older MSRV.

Unpin time

---

.github/workflows/ci.yml
src/lib.rs

I recommend reviewing this branch commit-by-commit.
There are no functional changes to the code, just CI improvements.

project: misc CI improvements.

---

.github/workflows/ci.yml
Cargo.toml
tests/botan.rs

In #118, windows CI was added but the botan specific tests were disabled as the build for rust doesn't work.
I'm opening this PR for future discussion and work on botan support on the windows CI. The goal is to get the CI green, and until then it can't be merged.

Enable botan CI on windows

---

src/lib.rs
tests/generic.rs

This branch updates a couple places that were writing x509 extensions by hand to use the existing `write_x509_extension` helper instead. 
Since custom extensions are a bit trickier a unit test for custom extensions in CSRs and certificates is added before refactoring the existing code to use the helper. This helps ensure the change is a no-op from the perspective of users.
With the updated test, it was possible to demonstrate a bug similar to https://github.com/rustls/rcgen/issues/122. The CSR serialization logic requiring SANs to be present in order to emit the custom extensions into the CSR PKCS9 extension request attribute. This branch fixes the issue.

lib: use ext helper in more places, test custom exts.

---

src/key_pair.rs

Currently, the `alg` field is restricted to the crate's scope. 
Provide a public function to access signature algorithm.

key_pair: add function to retrieve signature algorithm

---

CHANGELOG.md

To support https://github.com/rustls/rcgen/issues/156 this commit updates `CHANGELOG.md` with some notes for the upcoming 0.11.2 release.
I've omitted changes that are crate internal (refactorings, dependency updates, CI changes, comment fixes, etc) and focused on the changes I suspect are most meaningful to downstream consumers. As discussed in #156 I've also omitted explicit credit for features contributed by a maintainer (est31, djc or myself).

docs: update CHANGELOG for pending 0.11.2 release

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Closes #156.
This is the first release of rcgen at its new home in the `rustls` github organization. I want to use this opportunity to thank @cpu , @djc and the other rustls members for their help with maintaining rcgen and letting rcgen join the `rustls` organization.

Release 0.11.2

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
examples/rsa-irc-openssl.rs
examples/rsa-irc.rs
src/crl.rs
src/key_pair.rs
src/lib.rs
tests/generic.rs
tests/openssl.rs
tests/webpki.rs

In 0.11.2 the `src/crl.rs` and `src/key_pair.rs` modules were unconditionally importing `crate::ENCODE_CONFIG`, but this is only present when building with the optional `pem` feature. Additionally the crate example binaries, doc examples, and unit tests were often implicitly depending on `pem`, breaking compilation with `--no-default-features`.
This branch adds the correct import feature cfg gates, adds CI coverage for `--no-default-features` testing and clippy, fixes all of the various implicit `pem` dependencies, and updates `CHANGELOG.md` for a point release to include the fixes.
Resolves https://github.com/rustls/rcgen/issues/161

fix import errors for builds w/o optional pem feature

---

CHANGELOG.md
src/crl.rs
src/csr.rs
src/error.rs
src/key_pair.rs
src/lib.rs
src/sign_algo.rs
tests/generic.rs
tests/webpki.rs

Error types of upstream crates often need to be referred to in several places like composite `Error` enums. Having the type just named `Error` and exported at the root makes this really easy by just fully-qualifying it, in our case `rcgen::Error`. This saves the user from having to add an additional `use rcgen::` line and is unambiguous.
We provide a type-alias to make the rename a non-breaking change, meaning it can be released immediately before other breaking changes like the [upgrade to `ring 0.17`](https://github.com/rustls/rcgen/pull/166) for example.

Rename `Error` type

---

.github/workflows/ci.yml

A possible alternative to https://github.com/rustls/rcgen/pull/168. This commit adds a caching step to the `build-windows`, `build` and `coverage` jobs of the GitHub actions CI configuration.
We key based on:
1. Runner OS
2. Rust toolchain
3. Hash of Cargo.lock
This is largely 1:1 with the [Cache action Rust Cargo docs](https://github.com/actions/cache/blob/main/examples.md#rust---cargo), but for the Windows build we also include the `$VCPKG_DEFAULT_BINARY_CACHE` to cache the result of `vcpkg` installation.

ci: add caching w/ actions/cache@v3

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/error.rs
src/key_pair.rs
src/lib.rs
tests/webpki.rs

Reboot of https://github.com/rustls/rcgen/pull/98.
This PR is a breaking change because the `RcgenError::RingKeyRejected` variant is changed AND because `ring` is part of the public API via the `From` impl for `RcgenError`.

Upgrade to `ring` `0.17`

---

Cargo.toml
examples/sign-leaf-with-ca.rs

Generate two certificates and sign the second with the first. Addresses #79 and #89.

Add example of generating a cert chain

---

rcgen/CHANGELOG.md
rcgen/src/lib.rs

In #167, the error type was renamed from RcgenError to rcgen::Error.
Make sure the compatibility alias uses the correct name.

Fix error compatibility alias

---

Cargo.toml
rcgen/Cargo.toml
rcgen/src/lib.rs
rcgen/tests/generic.rs

This branch adds basic support emitting and parsing distinguished name values that are Ia5Strings. For example, email address attributes in a certificate subject distinguished name.
Note that because of #181 this code will panic when emitting invalid Ia5String values. This problem is general to rcgen's handling of ASN.1 string types and so isn't addressed with additional care in this branch. A broader rework is required.
Along the way I also fixed a warning from https://github.com/rustls/rcgen/pull/176 related to where we were defining the custom `profile.dev.package.num-bigint-dig` profile metadata.
Resolves #180

basic Ia5String support for DistinguishedName values

---

Cargo.toml
rcgen/Cargo.toml

Given that rustls-cert-gen already specifies its version number (such that only one crate actually uses the workspace `version`) and that version numbers are generally pretty closely tied to specific crate's API, IMO it's better to avoid having a workspace-level crate version.

Don't use workspace-wide crate versions

---

codecov.yml

Turn off codecov leaving comments on PRs based on the [doc suggestion](https://docs.codecov.com/docs/pull-request-comments#disable-comment).
Resolves https://github.com/rustls/rcgen/issues/186

codecov: disable comments

---

.github/workflows/ci.yml
rcgen/examples/rsa-irc-openssl.rs
rcgen/examples/rsa-irc.rs
rcgen/src/lib.rs
rcgen/tests/botan.rs
rcgen/tests/generic.rs
rcgen/tests/openssl.rs
rcgen/tests/webpki.rs

While reviewing https://github.com/rustls/rcgen/pull/188 I wanted to confirm that example code was being built in CI. It turns out that it wasn't. Similarly we haven't been running `clippy` against test code, and so there was a number of findings to address.
This branch updates CI to:
* Remove `--all`.  This is a deprecated alias for `--workspace`, and `--workspace` is the default for a directory containing a workspace so it can be omitted.
* Use `--all-targets` whenever we run `cargo check`, `cargo test` or `cargo clippy`. This ensures coverage for both examples and unit tests.
In order for the `cargo clippy ... --all-targets` to succeed this branch addresses each of the findings that were present. I've done this with a separate commit per class of finding to make it easier to review. In …

Ensure CI covers examples and unit tests, fix clippy findings

---

rcgen/examples/simple.rs

This takes what was formerly `rcgen/src/main.rs` and moves it to the examples folder as `simple.rs`. It was split off from #185

new `simple` example for rcgen

---

README.md

Was needed before Rust edition 2018

readme: remove needless loc

---

rcgen/src/lib.rs

If using from_ca_cert_der/_pem, the key_identifier_method would always be set to Sha256, which is not always true. If using OpenSSL for example SHA1 would be used.
If the provided CA certificate contains a SubjectKeyIdentifier extension, then this option will be automatically set.
Fixes #195.

Add PreSpecified(Vec<u8>) option to KeyIdMethod.

---

.github/workflows/ci.yml
Cargo.lock
rcgen/Cargo.toml
rcgen/src/key_pair.rs
rcgen/src/lib.rs
rcgen/src/ring_like.rs
rcgen/src/sign_algo.rs
rustls-cert-gen/Cargo.toml

Starting from [0.22.0, `rustls`](https://github.com/rustls/rustls/releases/tag/v%2F0.22.0), ecosystem has started supporting [`aws-lc-rs`](https://github.com/aws/aws-lc-rs) as crypto back-end. This latter replaces crypto functionalities provided by `ring`.
The main reason behind this is to provide [FIPS](https://en.wikipedia.org/wiki/FIPS_140-2) compliance in the future via `aws-lc`:
> Optional support for cryptography from [aws-lc-rs](https://github.com/aws/aws-lc-rs). Once the certification process completes , we will support FIPS mode using aws-lc-rs.
---
This PR is implementing the [same](https://github.com/rustls/rustls/blob/4d1b762b5328a1714862ba73ec72d5522fe0c049/rustls/Cargo.toml#L19) supporting mechanism.
In short:
* if cfg(feature = "ring") -> ring   (this will be the default)
* …

Add support for `aws_lc_rs` as crypto backend

---

rcgen/CHANGELOG.md

For release notes see the changelog.
fixes #199

Release 0.12.0

---

.github/workflows/ci.yml
rcgen/src/key_pair.rs
rustls-cert-gen/Cargo.toml

Currently trying to build like this:
```
cargo build -p rcgen --no-default-features --features ring
```
will fail because it can't find `pem::PemError` or `Error::PemError`.
Simply adding a `cfg` guard on this implementation fixes the issue.

Allow building without the `pem` crate feature

---

rcgen/src/lib.rs

By default, s/n is generated taking digest of pub-key of the certificate.
However, if the slice number representation is a negative number, then `write_bigint_bytes` is going to append an additional `0`-byte to ensure the positive sign.
See: https://github.com/qnighy/yasna.rs/blob/b7e65f9a4c317494cce2d18ea02b3d6eaaea7985/src/writer/mod.rs#L493-L495
So it is possible the bigint encoding will take 21 bytes instead of 20.
This CR sets MSB of digest to `0` to ensure encoding will take exactly 20 bytes

ensure default serial generation fits 20 bytes

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
rcgen/Cargo.toml
rustls-cert-gen/Cargo.toml
rustls-cert-gen/README.md
rustls-cert-gen/src/cert.rs
rustls-cert-gen/src/lib.rs
rustls-cert-gen/src/main.rs

This is basically #185 minus #188 and #189. The structure also differs as sub modules have been inlined in `main.rs` and `cert.rs`. `anyhow` has also been added as a dependency to replace the `Result` alias.
Closes #175

A functional `rustls-cert-gen` with basic parameters.

---

.github/workflows/ci.yml
rustls-cert-gen/Cargo.toml

From the release 0.12 of rcgen https://github.com/rustls/rcgen/pull/202 , we must now choose `ring` or `aws_lc_rc` as a feature.
Because `rustls_cert_gen` has `default-features = false`,  its build is currently broken.
~This PR activate  `aws_lc_rc` feature, because soon it will get RSA key generation support https://github.com/aws/aws-lc-rs/issues/296 , so it will provide more options.~ Edit: we switched to using ring to match the rcgen default.
But we could also change it to default to whatever `rcgen` default or use `ring` as default depending on your preferences.

choose a crypto_provider for rustls_cert_gen

---

rcgen/src/lib.rs

As stated in [RFC 5280§4.2.1.12](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.12) in
> Key purposes may be defined by any organization with a need.  Object
identifiers used to identify key purposes MUST be assigned in
accordance with IANA or ITU-T Recommendation X.660 [[X.660](https://datatracker.ietf.org/doc/html/rfc5280#ref-X.660)].
This corresponds to the other variant of the  [x509_parser::extensions::ExtendedKeyUsage](https://docs.rs/x509-parser/latest/x509_parser/extensions/struct.ExtendedKeyUsage.html#structfield.other)
This PR add support for others oid in the extended key usage.

add support for other oid in the extended key usage

---

Cargo.lock
rcgen/CHANGELOG.md
rcgen/Cargo.toml

This PR targets a `rel-0.12` branch to prepare a 0.12.1 point release that includes two changes since 0.12.0:
* https://github.com/rustls/rcgen/pull/203 - ensure default serial generation fits 20 bytes
* https://github.com/rustls/rcgen/pull/204 - Allow building without the pem crate feature
Resolves https://github.com/rustls/rcgen/issues/218

v0.12.1 preparation

---

rcgen/CHANGELOG.md

Forward-porting the changelog update from https://github.com/rustls/rcgen/pull/219 to `main`.

docs: update CHANGELOG for 0.12.1

---

.github/workflows/ci.yml
rcgen/Cargo.toml
rcgen/src/crl.rs
rcgen/src/error.rs
rcgen/src/key_pair.rs
rcgen/src/lib.rs
rcgen/src/ring_like.rs
rcgen/src/sign_algo.rs
rcgen/tests/botan.rs
rcgen/tests/generic.rs
rcgen/tests/util.rs
rcgen/tests/webpki.rs

This makes all of the crypto libraries optional. My use case requires simply generating the binary ASN.1 structures and all cryptography is handled externally with HSMs.
This change removes unnecessary code and build complexity (for example, I'm targeting WASM, and I need to take extra steps to build the dependencies I don't need).
Note to the maintainer: this is a clean (and ideally better) rework of a previous PR, #207. Because I deleted the older and messier branch, the previous PR couldn't be updated, so I closed it.

Support compiling without cryptography primitives

---

codecov.yml

By default Codecov leaves comments on diffs as ["annotations"](https://docs.codecov.com/docs/common-recipe-list#disable-github-check-run-annotations). These are separate from comments, which we disabled previously (https://github.com/rustls/rcgen/pull/187). This commit disables the annotations as well. Too much noise-to-signal right now.
Resolves https://github.com/rustls/rcgen/issues/186

codecov: disable pull-request annotations

---

.github/workflows/ci.yml

Fixes [CI failures](https://github.com/rustls/rcgen/actions/runs/7920382172/job/21623293107) for the associated task.

ci: sync nightly for check-external-types

---

rcgen/src/key_pair.rs
rcgen/src/lib.rs

The `std::convert::TryFrom` import is part of the rust 2021 edition prelude and so importing it explicitly is redundant. This results in a [clippy error](https://github.com/cpu/rcgen/actions/runs/7963608666/job/21739553339) for CI builds using nightly:
```
warning: the item `TryFrom` is imported redundantly
--> rcgen/src/lib.rs:41:5
|
41  | use std::convert::TryFrom;
|     ^^^^^^^^^^^^^^^^^^^^^
|
::: /home/daniel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/prelude/mod.rs:129:13
|
129 |     pub use core::prelude::rust_2021::*;
|             ------------------------ the item `TryFrom` is already defined here
|
= note: `#[warn(unused_imports)]` on by default
```

proj: fix new clippy unused imports finding

---

rcgen/src/crl.rs
rcgen/src/lib.rs
rcgen/tests/botan.rs
rcgen/tests/generic.rs
rcgen/tests/openssl.rs
rcgen/tests/webpki.rs

Aligning with the [API guidelines](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter).

Remove get_() prefixes from method names

---

Cargo.lock
rcgen/Cargo.toml
rcgen/src/key_pair.rs
rcgen/src/sign_algo.rs
rustls-cert-gen/src/cert.rs

Uses the recently added RSA key generation support of aws-lc-rs.
Fixes #229

Add RSA key generation

---

.github/workflows/ci.yml
Cargo.lock
rcgen/Cargo.toml

Following the same direction of `rustls`, from the latest version ([0.23.0](https://github.com/rustls/rustls/releases/tag/v%2F0.23.0)):
> Default cryptography provider changed to [aws-lc-rs](https://crates.io/crates/aws-lc-rs).
> [...]
> Support for FIPS validated mode with [aws-lc-rs](https://crates.io/crates/aws-lc-rs)
This PR is composed by 2 commits:
* Adding `fips` feature to enable `aws_lc_rs/fips`
* Changing default crypto backend from `ring` to `aws_lc_rs`

FIPS support

---

rcgen/src/certificate.rs
rcgen/src/crl.rs
rcgen/src/lib.rs
rcgen/src/oid.rs
rcgen/src/sign_algo.rs

Following up on some suggestions from https://github.com/rustls/rcgen/pull/237#discussion_r1516701656.

Inline oid module

---

Cargo.lock
Cargo.toml
rcgen/Cargo.toml
rcgen/src/certificate.rs
rcgen/src/csr.rs
rcgen/src/key_pair.rs
rcgen/tests/webpki.rs
rustls-cert-gen/Cargo.toml
rustls-cert-gen/src/cert.rs

Use [`pki_types`] to improve the interoperability with the `rustls` ecosystem and make types pretty clear, as suggested by https://github.com/rustls/rcgen/pull/170#issuecomment-1849565550. 
To fully get rid of the `pem` dependency (by replacing it by `rustls_pemfile`), I think those further actions will be needed:
- add `CertificateSigningRequestDer` to  [`pki_types`]
- add a `Csr` variant to [rustls_pemfile::Item] which is a newtype of ` CertificateSigningRequestDer` 
- add some encoding capability to [rustls_pemfile](https://docs.rs/rustls-pemfile/latest/rustls_pemfile/index.html#), basically it would mean adding headers ("---- BEGIN ----") and handle well line ending.
Please let me know if I miss something and if you think this goes in the right direction.
I'm open to submit following …

Use pki_types to improve the interoperability with the rustls ecosystem 

---

rcgen/src/key_pair.rs
rcgen/src/lib.rs

The new `KeyPair::generate_rsa_for` fn from https://github.com/rustls/rcgen/pull/230 is only usable outside the crate if the `key_pair::RsaKeySize` type is exported from `lib.rs` since `key_pair` is a private module.

lib: export key_pair::RsaKeySize

---

rcgen/src/certificate.rs
rcgen/src/crl.rs
rcgen/src/csr.rs
rcgen/src/key_pair.rs
rcgen/src/sign_algo.rs
rcgen/tests/botan.rs
rcgen/tests/generic.rs
rcgen/tests/openssl.rs
rcgen/tests/util.rs
rcgen/tests/webpki.rs

Updates the CRL creation flow along the lines of #205.

Serialize CRL parameters into CertificateRevocationList

---

rcgen/src/certificate.rs

This PR is remove a warning as requested on [241](https://github.com/rustls/rcgen/pull/241#issuecomment-2006224451).
Alternatively I could use `use super::super::*` in relevant tests and get rid of the conditional compilation. I feel that way could be easier to maintain.

Fix unused import warning

---

rcgen/src/key_pair.rs
rcgen/tests/openssl.rs
rcgen/tests/webpki.rs
rustls-cert-gen/src/cert.rs

This branch pulls out the [suggested rename](https://github.com/rustls/rcgen/pull/242#issuecomment-2006944259) from https://github.com/rustls/rcgen/pull/242 in order to unblock release planning (https://github.com/rustls/rcgen/issues/236) while the more generic key pair constructor is worked out.

key_pair: emphasize PKCS8 input requirement in constructor fn names

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
rcgen/Cargo.toml
rcgen/src/key_pair.rs
rcgen/src/oid.rs
rcgen/src/sign_algo.rs
rcgen/tests/botan.rs
rcgen/tests/generic.rs
rcgen/tests/openssl.rs
rustls-cert-gen/Cargo.toml
rustls-cert-gen/src/cert.rs

Support ECDSA_P521_SHA512 when using aws_lc_rs feature

---

rcgen/src/certificate.rs
rcgen/src/crl.rs
rcgen/src/csr.rs

These are non-semver-breaking so they don't need to block the release, but I think they are a natural addition to API changes we've already made (moving `KeyPair` out of `CertificateParams` and storing `*Der` types internally).

Minor API tweaks

---

rcgen/Cargo.toml
rcgen/src/key_pair.rs
rcgen/src/lib.rs
rcgen/src/oid.rs
rcgen/src/ring_like.rs
rcgen/src/sign_algo.rs
rcgen/tests/botan.rs
rcgen/tests/generic.rs
rcgen/tests/openssl.rs
rustls-cert-gen/src/cert.rs

Prefer aws-lc-rs over ring if both are enabled

---

rcgen/CHANGELOG.md
rcgen/docs/0.12-to-0.13.md

I've included substantially more detail in this CHANGELOG update compared to previous. To try and keep the top level content manageable, while also balancing making updates as friction-less as possible, I've split off some separate migration help to its own document.
I've done my best to flag all of the important changes but would appreciate more eyes to make sure I haven't missed or misrepresented anything. Like previous updates I've called out contributions by external folks and not those by core maintainers.

docs: update CHANGELOG for 0.13.0

---

rustls-cert-gen/Cargo.toml

Encountered this error while trying to `cargo publish` rustls-cert-gen:
```
djc-2021 main rustls-cert-gen $ cargo publish
Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `rcgen` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```

Set library version for CLI crate

---

rustls-cert-gen/Cargo.toml

```
djc-2021 main rustls-cert-gen $ cargo publish
Updating crates.io index
warning: manifest has no documentation, homepage or repository.
See https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata for more info.
```
(I aborted before it completed publishing.)

cli: add more Cargo metadata

---

rcgen/src/certificate.rs
rcgen/src/crl.rs
rcgen/src/csr.rs
rcgen/src/lib.rs

Without changing the public API, prepare for splitting out a type that is capable of signing.

Clarify internal data dependencies for signing APIs

---

rcgen/src/certificate.rs
rcgen/src/csr.rs
rcgen/tests/webpki.rs

This pull requests adds parsing of most of the extended key usage parameters, except for Other.

Pass extended key usage parameters when importing CertificateSigningRequestParams 

---

.github/workflows/ci.yml
Cargo.lock

For `cargo-check-external-types`, the upstream project cut a [0.1.12 release](https://github.com/awslabs/cargo-check-external-types/releases/tag/v0.1.12) that now pins Rust nightly-2024-05-01. This commit updates CI to match.
For the `time` dep, a bump in the `Cargo.lock` was required to fix the project build w/ nightly.
Lastly, the project's builds of `main` using nightly are hitting an upstream bug (rust-lang/rust#125474), take the same workaround we landed in Rustls (https://github.com/rustls/rustls/pull/1971) to unbreak the build while this is sorted out.

ci: update cargo-check-external-types toolchain, fix build

---

.github/workflows/ci.yml

This reverts commit 74ecacab0c4853ac1a8908669111f286dfeab933 from https://github.com/rustls/rcgen/pull/276. Latest nightly builds/tests without issue.

Revert "ci: temp. pin nightly to avoid ICE"

---

rcgen/src/csr.rs
rcgen/tests/generic.rs

Fixes https://github.com/rustls/rcgen/issues/280.

Expose `algorithm` field on `PublicKey`

---

rcgen/src/crl.rs

Nightly rustdoc flags these as non-standard markdown, and they don't render as nicely as just using a link. See also https://github.com/rustls/rustls/pull/2033, https://github.com/rustls/webpki/pull/268
Fixes [build errors on main](https://github.com/rustls/rcgen/actions/runs/9821174655/job/27116566286).

crl: avoid markdown footnotes

---

Cargo.lock
Cargo.toml
rcgen/Cargo.toml
rustls-cert-gen/Cargo.toml

Rcgen doesn't require `aws-lc-rs`'s default features, so disabling them removes some dependencies.

Disable default features for `aws-lc-rs`

---

rcgen/src/certificate.rs
rcgen/src/csr.rs
rcgen/src/lib.rs
rcgen/tests/generic.rs
rcgen/tests/webpki.rs

I've added KeyUsage support to CSR generation, as well as a number of improvements to the parsing and writing of DER-encoded key usages.
These commits can be reviewed in order!
(Coming from https://github.com/rustls/rcgen/issues/285)

Add KeyUsage support to CSR generation

---

rcgen/tests/openssl.rs

We discovered this as a build failure on i686 when packaging this crate for Fedora Linux.
It looks like `openssl::asn1::Asn1Time::from_unix` takes a 64-bit number on 64-bit platforms only, and a 32-bit number on 32-bit platforms.
This PR adds the suggestion that's made by rustc - add `.try_into().unwrap()` to explicitly convert to an u32 (and fail if the number is out of range).

Fix compilation issues of OpenSSL tests on 32-bit architectures

---

rcgen/src/certificate.rs
rcgen/src/csr.rs
rcgen/src/error.rs
rcgen/src/key_pair.rs
rcgen/src/lib.rs

Takes #288 and addresses the comments.
Fixes #282.

Enable signing without private key

---

rcgen/src/certificate.rs

The current wording suggests there's such thing as a "self-signed" CSR, which isn't the case. This is minor, but it throws me off every time I read it.

Clarify CSR signing docs

---

.github/workflows/ci.yml

See the upstream release notes:
https://github.com/awslabs/cargo-check-external-types/releases/tag/v0.1.13
Fixes [build break](https://github.com/rustls/rcgen/actions/runs/11617500782/job/32352862400) of the associated task on main.

ci: adjust nightly for cargo-check-external-types

---

rcgen/src/certificate.rs
rcgen/src/lib.rs
rcgen/tests/generic.rs

Coming from https://github.com/rustls/rcgen/issues/285, this PR adds PKCS#10 attributes to rcgen's CSR serialization logic.
Of course, rcgen has already implicitly supported at most one attribute in the form of PKCS#9's extensionRequest[^1], but this allows you to add others.
I haven't split up the commits yet in anticipation of review comments, but the rough changes are (as of writing):
- Add an `Attribute` type that represents an RFC 5280[^2]/RFC 2986[^3] (take your pick) ATTRIBUTE.
- Add a `custom_csr_attributes` field to `CertificateParams`, of type `Attribute`
- Add serialization logic for `custom_csr_attributes` in `CertificateParams::serialize_request`
- Add an end-to-end/roundtrip test for CSR serialization with custom attributes
- Add to and update existing CSR serialization …

Add PKCS#10 attributes to CSR serializer

---

README.md
rcgen/src/lib.rs

Update README.md example to match what's in `lib.rs`

---

rcgen/src/certificate.rs

I had the issue that I wanted to use an issuer that was a `CertificateParams`, not a `Certificate` (because CertificateParams can be deserialized from file, but Certificate can not). The best solution I've found is to change the signature to accept `&impl AsRef<CertificateParams>`, and then implement that `AsRef` for both `Certificate` and `CertificateParams`.
I think this is also a backwards-compatible change, but I'm not 100% sure.

change signature of signed_by to accept &impl AsRef<CertificateParams> issuer

---

rcgen/src/certificate.rs

As suggested by @est31 in https://github.com/rustls/rcgen/pull/307#issuecomment-2571357329 (sorry for the hasty merge there).

Clarify CertificateParams::signed_by() docs

---

rcgen/src/certificate.rs
rcgen/src/crl.rs
rcgen/src/csr.rs

Completes #307 by applying the same treatment to `csr` and `crl`.
Also improves `CertificateParams::signed_by` issuer from `AsRef<Self>` to `AsRef<CertificateParams>`, because I think it's irrelevant that the issuer is the same type as the CertificateParams being signed, thus `Self` should not be used.

refactor: Generalize csr/crl signed_by to take &impl AsRef issuer

---

rcgen/src/certificate.rs
rcgen/tests/generic.rs

Fixes https://github.com/rustls/rcgen/issues/310

Fix: mark SAN as critical when subject is empty

---

rcgen/src/key_pair.rs

This closes https://github.com/rustls/rcgen/issues/313 by manually implementing `Debug` for `KeyPair` to elide the PKCS#8 private key bytes that would otherwise be displayed for its `serialized_der` member.
I did this similarly to [rustls/pki-types](https://github.com/rustls/pki-types).
```rust
KeyPair { kind: EcdsaKeyPair { public_key: EcdsaPublicKey("040888dd433ae8faffeed2cb21ddad501dd470167bd8dfd48f90242d1b1fca1822c8e4cd53d6e993c61f2cf4a5b1a6f270a57c0836dfb9273d3df1c5677020e419") }, alg: PKCS_ECDSA_P256_SHA256, serialized_der: [48, 129, 135, 2, 1, 0, 48, 19, 6, 7, 42, 134, 72, 206, 61, 2, 1, 6, 8, 42, 134, 72, 206, 61, 3, 1, 7, 4, 109, 48, 107, 2, 1, 1, 4, 32, 17, 196, 129, 135, 217, 93, 38, 238, 38, 166, 163, 117, 235, 39, 184, 165, 40, 117, 21, 219, 111, 214, 131, 91, 103, 42, 103, …
```

Elide private key in KeyPair Debug impl

---

rcgen/src/certificate.rs

Make `Certificate` cloneable (derive `Clone`)
Part of https://github.com/rustls/rcgen/issues/17
> `CertificateParms` is clone now. `Certificate` is not, but I think we'd accept a PR to make it so.
> 
> *-- https://github.com/rustls/rcgen/issues/17#issuecomment-2025329460*
In a similar vein for deriving `Debug` for `Certificate` in https://github.com/rustls/rcgen/commit/362e78a18495a6c7bcbd66f46e7ee56f28f88c5a

Make `Certificate` cloneable (derive `Clone`)

---

Cargo.lock
rcgen/Cargo.toml

Prepare a release. Changes:
* Update dependencies by djc in https://github.com/rustls/rcgen/pull/305
* Add link to GitHub releases by djc in https://github.com/rustls/rcgen/pull/304
* change signature of signed_by to accept &impl AsRef<CertificateParams> issuer by audunhalland in https://github.com/rustls/rcgen/pull/307
* Clarify CertificateParams::signed_by() docs by @djc in https://github.com/rustls/rcgen/pull/308
* refactor: Generalize csr/crl signed_by to take &impl AsRef issuer by audunhalland in https://github.com/rustls/rcgen/pull/312
* Fix: mark SAN as critical when subject is empty by howardjohn in https://github.com/rustls/rcgen/pull/311
* Elide private key in KeyPair Debug impl by lvkv in https://github.com/rustls/rcgen/pull/314
* derive Debug for non-sensitive struct types by …

rcgen: bump version to 0.13.3

---

rcgen/src/certificate.rs
rcgen/src/crl.rs
rcgen/src/csr.rs

Reverts #307 and #312 because they broke semver (#324) .
I'll make a followup that re-introduces this feature using another set of methods.

Revert impl AsRef issuer

---

Cargo.lock
rcgen/Cargo.toml
rcgen/src/lib.rs
rcgen/src/string.rs
rustls-cert-gen/Cargo.toml

Looking at the rustdoc, it's a bit weird to see the string types mixed up with certificate related stuff.
The rename was done because it follows the way `std` names its modules.

Move string types to separate module

---

rcgen/src/certificate.rs
rcgen/src/csr.rs
rcgen/src/lib.rs
rustls-cert-gen/src/cert.rs

This takes the processing steps for transforming an `x509_parser::Certificate` into `CertificateParams` and distributes them over the relevant element's types, in preparation for splitting `from_ca_cert_pem()` and `from_ca_cert_der()` from `CertificateParams` (to make it statically obvious that their use is only intended to build an `Issuer`).

Distribute methods for parsing params elements from x509

---

rcgen/src/certificate.rs
rcgen/src/crl.rs
rcgen/src/csr.rs
rcgen/src/error.rs
rcgen/src/lib.rs
rcgen/src/sign_algo.rs
rcgen/tests/openssl.rs
rustls-cert-gen/src/cert.rs

Coming from https://github.com/rustls/rcgen/issues/340, this PR derives `Clone` and `Copy` to align rcgen more closely with Rust's [API guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits). Here's how I went about this:
1. Derive `Clone` for as many types as possible in a full codebase pass (finding types by basically grepping for `struct ` and `enum `). Keep making passes until no more types can derive it.
2. Ditto for `Copy`
I've intentionally opted to derive these traits eagerly at first so that types that we _don't_ want to derive `Clone` or `Copy` for will come up in this review. I think most of these make sense, but I could see some being not desirable—e.g., `Copy` for `SignatureAlgorithmParams`.

Eagerly derive Clone, Copy, where possible

---

.github/workflows/ci.yml
rcgen/Cargo.toml
rcgen/examples/rsa-irc-openssl.rs
rcgen/tests/openssl.rs

For a while now, build-windows has been failing with some non-obvious issues.
First failing run:
- https://github.com/rustls/rcgen/actions/runs/15052227395
Last working run:
- https://github.com/rustls/rcgen/actions/runs/15028005622
Ostensibly, nothing changed between these two runs (including the GitHub runner image and operating system and the `Cargo.lock` file), so I'm not sure what's going on here. Given the way we use OpenSSL (only to test that our generated artifacts are compatible with OpenSSL), I think it's fine to limit such testing to `unix` platforms only, avoiding a bunch of complexity from building OpenSSL on Windows.

tests: only test against openssl on Unix

---

.github/workflows/ci.yml

These mostly seem to cause quite a bit of noise, which makes it harder to see what else is going on.

ci: drop --verbose from cargo invocations

---

rcgen/src/key_pair.rs

As suggested in https://github.com/rustls/rcgen/issues/357#issuecomment-3017557725.
I think we should keep the name as is. While it might be a bit jargony, it's also precise in a way that I think will be helpful.

Tweak docstring for PublicKeyData::subject_public_key_info()

---

rcgen/src/lib.rs

After upgrading a bunch of downstream code, this stands out as something that would make downstream code simpler.

Add a CertifiedIssuer

---

rcgen/src/lib.rs

Hey `rcgen` folks!
I must say I really like what you've done with the new API changes, but I'm really missing a way to sign certificates without giving the issuer ownership of the `KeyPair` (especially frustrating since it's not `Clone`).
Maybe I missed an alternative (maybe there's a newtype around a reference that directly impls `SigningKey`), but this seems like a straight forward enough change.
Do keep in mind that if you accept this PR, you're probably locking yourself into having these `MaybeOwned` in the internal type representation (just thought I'd warn you :) ).
Note: feel free to reject this PR if you don't want that extra surface, I'm gonna newtype `&KeyPair` to get that copy-less use in my project :)

Provide a non-owning constructor for `Issuer`

---

rcgen/src/sign_algo.rs

Changed probably mistakenly copied `SHA-256` to `SHA-384`.

docs: fix typo in `PKCS_RSA_SHA384` doc comment

---

Cargo.lock
rcgen/Cargo.toml
rcgen/src/certificate.rs

Key usage purpose encoding regressed in #287.
I don't (yet) really know what I'm doing here, just implementing @ctz's suggestion from the issue to keep this moving.
Anyone want to suggest some tests that would prevent this from regressing again? There are some tests in https://github.com/rustls/rcgen/pull/287/files#diff-1340717e703c8244b2ad18d09955bd825f1565daee83f900a26a5c956b57c125R380 but we should have something that catches this.
Fixes #368.

Fix regression in key usage purpose encoding

---

Cargo.lock
rcgen/Cargo.toml
rcgen/src/certificate.rs
rcgen/src/crl.rs
rcgen/src/key_pair.rs
rcgen/src/lib.rs

Fixes #373, hopefully.
Implement `SigningKey` for `&impl SigningKey` to make `Issuer` more broadly useful.

Forward signing and public key data through references
